"use client";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../styles/globals.css"
// const inter = Inter({ subsets: ["latin"] });

import Head from 'next/head'
import Header from './layouts/header'
import Footer from './layouts/footer'

import type { AppProps } from 'next/app'
import Layout from './layouts'
import { Provider } from 'react-redux'
import { store } from '../redux/store'
import { fetchUser } from '../redux/session/sessionSlice'
import { toast } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

store.dispatch(fetchUser())
toast.configure({
  autoClose: 8000,
  draggable: false,
  position: toast.POSITION.TOP_CENTER,
})

export default function App({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <html lang="en">
        {/* <body className={inter.className}> Helvetica Neue", Helvetica, Arial, sans-serif */}
        <body>
          <div className="App">
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
              <script src="/jquery-1.11.0.min.js"></script>
              <script src="/bootstrap.min.js"></script>
            </Head>

            <Header />

            <div className="container">
              { children }

              <Footer />
            </div>
          </div>
        </body>
      </html>
    </Provider>
  );
}
